# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iTruyen' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iTruyen
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'SkyFloatingLabelTextField', '~> 3.0'
pod 'ReachabilitySwift'
pod 'Kingfisher', '~> 5.0'
end
